Improve building the PDF via Makefile
input-output-hk/formal-ledger-specifications pull request #160
Opened 2023-08-01 11:19 UTC by WhatisRT

# Description

This fixes `Makefile` being outdated & improves `shell.nix` to be able to use `Makefile` more conveniently.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] Code is formatted according to [CONTRIBUTING.md](https://github.com/input-output-hk/formal-ledger-specifications/blob/master/CONTRIBUTING.md)
- [x] Self-reviewed the diff

2023-08-01 21:20 UTC, williamdemeo requested changes
It works, but I did need to run `nix-shell --command make` three times to make the references resolve.  Would it be hard to make it so that the latex compilation step is executed as many times as needed to resolve all refs?

2023-08-01 21:24 UTC, williamdemeo commented
Also, the pdf ends up in the top level directory in the file `PDF.pdf`.  Should it not be called `cardano-ledger.pdf` ...and maybe for consistency should it end up in a `result` directory?

2023-08-02 11:32 UTC, WhatisRT commented
The `result` directory is a nix thing, so I prefer not messing with that. I've renamed it to `cardano-ledger.pdf` & switched to `latexmk`.

2023-08-02 16:07 UTC, williamdemeo approved these changes
Works great now.  Nice work!

2023-08-02 16:07 UTC, merged

2023-08-02 23:03 UTC, williamdemeo commented
I think your last rebase may have clobbered your improvements to the Makefile.  Sorry I missed that before merging.  I'll open a new PR with your previous Makefile mods.