Other pdf cleanup items: Fig 21 too big
input-output-hk/formal-ledger-specifications pull request #294
Opened 2023-11-07 23:55 UTC by williamdemeo

# Description

This addresses one item of issue #289

We simply split off the latter part of the figure into its own figure which appears on the succeeding page.

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] Code is formatted according to [CONTRIBUTING.md](https://github.com/input-output-hk/formal-ledger-specifications/blob/master/CONTRIBUTING.md)
- [X] Self-reviewed the diff

2023-11-08 13:01 UTC, WhatisRT requested changes
Thank you! While looking at the PDF, this revealed that a bunch of other stuff isn't all that great right there, could you include those here?

2023-11-08 20:38 UTC, williamdemeo commented on src/Ledger/Utxo.lagda
>  ≟-∅ᵇ X = ¿ X ≡ ∅ ¿ᵇ
How about the `data inInterval` type?  It's used later in code that appears in a figure in the pdf, so I suppose we don't want to hide its definition... or do we?

2023-11-09 10:57 UTC, WhatisRT commented on src/Ledger/Utxo.lagda
>  ≟-∅ᵇ X = ¿ X ≡ ∅ ¿ᵇ
Yeah, it should be in the PDF (maybe we should do some tweaks about it later though)

2023-11-09 12:38 UTC, WhatisRT approved these changes

2023-11-09 12:38 UTC, merged