WIP
input-output-hk/formal-ledger-specifications pull request #71
Opened 2023-03-20 13:19 UTC by Soupstraw

2023-03-20 15:01 UTC, WhatisRT commented on src/Axiom/Set/Map.agda
> +  update x (just y) m = m ∪ᵐˡ (❴ x , y ❵ , helper)
There's also a function that constructs a singleton map, so you don't need `helper` at all

2023-03-22 13:34 UTC, WhatisRT commented on src/Axiom/Set/Map/Dec.agda
> +open import Algebra.Bundles
This is supposed to be imported by `Algebra`

2023-03-22 13:38 UTC, WhatisRT commented on src/Ledger/Deleg.lagda
> +  (Network KeyHash ScriptHash : Set)
Now that I look at this, I think it's better to require a `crypto : Crypto` here. That includes the hash types with their decidable equality. That also applies to `Ledger.Address`, but to do that there we should also adjust the LaTeX...

2023-03-28 11:01 UTC, WhatisRT requested changes
Great stuff! If any of the things I've pointed out is too much work right now, just leave a `TODO` or make an issue, I just don't want things to get lost.

2023-03-28 11:37 UTC, Soupstraw commented on src/Ledger/Deleg.lagda
> +    d ≥ requiredDeposit mc + requiredDeposit mc'
I like that idea!

2023-03-28 11:56 UTC, Soupstraw commented on src/Ledger/Deleg.lagda
> +    pp ⊢ ⟦ ❴ c , d ❵ᵐ ∪ᵐˡ dReps , ccKeys ⟧ᵛ ⇀⦇ deregdrep c ,VDEL⦈
Should I turn this into an equivalence or subtract the value on the RHS?

2023-03-28 14:06 UTC, Soupstraw commented on src/Ledger/Chain.lagda
>        acnt' = record acnt { treasury = Acnt.treasury acnt + UTxOState.fees utxoSt }
Added a TODO

2023-03-28 14:07 UTC, Soupstraw commented on src/Ledger/Utxo.lagda
> +totalDeposits : TxBody → Value
I added a TODO, because we'll have to implement folding over maps for that

2023-03-29 14:36 UTC, merged